type Artist @entity {
  id: ID!
  name: String!
  wallet: String!
  coverImageCid: String
  totalTracks: BigInt!
  totalSalesCount: BigInt!
  totalVolume: BigInt!
  createdAt: BigInt!
  updatedAt: BigInt!
  tracks: [Song!]! @derivedFrom(field: "artist")
  albums: [Album!]! @derivedFrom(field: "artist")
  sales: [Sale!]! @derivedFrom(field: "artist")
  mints: [MintEvent!]! @derivedFrom(field: "artist")
  events: [ArtistEvent!]! @derivedFrom(field: "artist")
}

type ArtistEvent @entity {
  id: ID!
  artist: Artist!
  eventType: String!
  data: String!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type Song @entity {
  id: ID!
  title: String!
  artist: Artist!
  album: Album
  duration: Int!
  ipfsHash: String!
  contentCid: String
  tokenId: BigInt
  owner: String
  price: BigInt
  isListed: Boolean!
  isMinted: Boolean!
  salesCount: BigInt!
  likeCount: BigInt!
  commentCount: BigInt!
  createdAt: BigInt!
  updatedAt: BigInt!
  sales: [Sale!]! @derivedFrom(field: "song")
  transfers: [TransferEvent!]! @derivedFrom(field: "song")
  mints: [MintEvent!]! @derivedFrom(field: "song")
  likes: [Like!]! @derivedFrom(field: "song")
  comments: [Comment!]! @derivedFrom(field: "song")
  events: [SongEvent!]! @derivedFrom(field: "song")
}

type SongEvent @entity {
  id: ID!
  song: Song!
  eventType: String!
  data: String!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type Sale @entity {
  id: ID!
  song: Song!
  artist: Artist!
  seller: String!
  buyer: String!
  price: BigInt!
  tokenId: BigInt!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type TransferEvent @entity {
  id: ID!
  song: Song
  tokenId: BigInt!
  from: String!
  to: String!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type MintEvent @entity {
  id: ID!
  song: Song!
  artist: Artist!
  minter: String!
  tokenId: BigInt!
  tokenUri: String
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type Like @entity {
  id: ID! # songId-userAddress
  song: Song!
  user: String!
  createdAt: BigInt!
  txHash: String!
}

type LikeEvent @entity {
  id: ID!
  song: Song!
  user: String!
  eventType: String! # "Liked" | "Unliked"
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type Comment @entity {
  id: ID! # commentId or txHash-logIndex
  song: Song!
  author: String!
  content: String!
  createdAt: BigInt!
  updatedAt: BigInt!
  txHash: String!
}

type CommentEvent @entity {
  id: ID!
  song: Song!
  author: String!
  eventType: String! # "CommentAdded" | "CommentRemoved"
  content: String
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type Album @entity {
  id: ID!
  title: String!
  artist: Artist!
  coverCid: String
  createdAt: BigInt!
  updatedAt: BigInt!
  tracks: [Song!]! @derivedFrom(field: "album")
  events: [AlbumEvent!]! @derivedFrom(field: "album")
}

type AlbumEvent @entity {
  id: ID!
  album: Album!
  eventType: String!
  data: String!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type Royalty @entity {
  id: ID!
  beneficiary: String!
  percentage: Int!
  song: String
  createdAt: BigInt!
  updatedAt: BigInt!
  events: [RoyaltyEvent!]! @derivedFrom(field: "royalty")
}

type RoyaltyEvent @entity {
  id: ID!
  royalty: Royalty!
  eventType: String!
  data: String!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type MarketplaceEvent @entity {
  id: ID!
  eventType: String!
  seller: String!
  buyer: String
  data: String!
  txHash: String!
  ledger: BigInt!
  createdAt: BigInt!
}

type IndexerHealth @entity {
  id: ID!
  network: String!
  contractType: String!
  lastProcessedLedger: BigInt!
  eventsProcessed: BigInt!
  errorCount: BigInt!
  lastError: String
  lagLedgers: BigInt!
  updatedAt: BigInt!
}
